### ISSUE TITLE
Adapt Slave to run Servo Benchmarks

### ISSUE THREAD

**Issue by JayNakrani** [dhananjay92/arewefastyet#1]
- [x] Modify `slave/build.py` to allow for building Servo.
- [ ] ~~Modify `slave/download.py` to allow for downloading Servo.~~
- [ ] Add executor for running servo-benchmarks in `slave/execute.py`
  - [ ] Manually run and figure out which benchmarks to run.
  - [ ] File issues for the benchmarks that don't work.
  - [ ] Figure out what data to send to _collector_.  (`slave/submitter.py`)

At the end of this, we should be able to run benchmarks and send info to _collector_. The _collector_ may not accept all the info, but that will be solved in next issue.

**Current Status:** 
- ~~Working on 'modifying `slave/download.py` to allow for downloading servo.'~~ Will do it once we start publishing automated builds for servo.
- Waiting for Issue [#3899](https://github.com/servo/servo/issues/3899) to be resolved. According to [Meeting of 2015-08-31](https://github.com/servo/servo/wiki/Meeting-2015-08-31#32-bit-rustc-snapshots), it should be done soon.

**Comment by JayNakrani** [comment]
@jdm: Do we publish automated builds like [Mozilla's Tinderbox builds](http://archive.mozilla.org/pub/mozilla.org/firefox/tinderbox-builds/mozilla-inbound-linux/latest/) for servo? 
It doesn't make sense to add the download functionality if we currently don't publish servo's builds.

**Comment by jdm** [comment]
The only builds we make are Android ones right now. I agree that this is an unnecessary piece of work until that changes.

**Comment by JayNakrani** [comment]
Okay, great then. We will do downloader later when we start publishing the builds. Updated the current status.

**Comment by h4writer** [comment]
"Figure out what data to send to collector:"
We use submitter.py to send data to the collector. I suggest looking at that file ;)

**Comment by jdm** [comment]
@dhananjay92 Theoretically there are now linux 32bit snapshots available, so you should see if you can progress further!

**Comment by JayNakrani** [comment]
@h4writer: Cool. Thanks! :smile: 

@jdm : Great! Working on it right away.

**Comment by JayNakrani** [comment]
Created PR #5 for the code review. I think it'll be a good practice to get these changes reviewed from either of you guys. So I will be creating these PRs just to get the code reviewed. The PRs will merge changes with branch `benchmarking-for-servo` on my own repo.
That branch will serve as the branch with all the final servo related changes to AWFY. If we decide to upstream these changes in future, it will be easier to merge that branch with @h4writer's `master`.

**Comment by JayNakrani** [comment]
So I added the executor for servo. See [01f6a9](https://github.com/dhananjay92/arewefastyet/commit/01f6a9). 
Command to execute the benchmark:

``` shell
cd slave/

python execute.py -b remote.dromaeo
```

It runs fine for the first time. But for the second time on wards, I get output like [this gist](https://gist.github.com/dhananjay92/39db7327922d1bfdda0d). `subprocess.Popen()` [returns errorcode -15](https://gist.github.com/dhananjay92/39db7327922d1bfdda0d#file-output-L9) and nothing in stdout, stderr! (See [exact line](https://github.com/dhananjay92/arewefastyet/commit/01f6a9#diff-975a8528dda6ea0a1090e7df97de1177R106))

I tried looking for causes, but couldn't find any. Do you see any reason why this might be happening? Is servo returning -15 or is this related to python?

**Comment by JayNakrani** [comment]
Aha! I think I found it! The problem is that [`killall()`](https://github.com/dhananjay92/arewefastyet/commit/01f6a9#diff-975a8528dda6ea0a1090e7df97de1177R100) does not wait for the command to finish & returns back immediately. This ends up killing the next servo started by [`Popen()`](https://github.com/dhananjay92/arewefastyet/commit/01f6a9#diff-975a8528dda6ea0a1090e7df97de1177R106)! Sending the fix right away.

**Comment by jdm** [comment]
Nice find :)
